// lib/sampleData.ts

import type { TrendTourRecord } from "@/types/trendTour";

function createSampleId(index: number): string {
  return `sample-${Date.now()}-${index}-${crypto.randomUUID()}`;
}

function toIsoDate(date: string) {
  return date.replaceAll("/", "-");
}

export function createSampleTrendTourRecords(): TrendTourRecord[] {
  const now = new Date().toISOString();

  const rows: Omit<TrendTourRecord, "id" | "createdAt" | "updatedAt">[] = [
    {
      year: 2023,
      prefecture: "茨城県",
      municipality: "大洗町",
      dataType: "アニメ",
      contentTitle: "ガールズ&パンツァー",
      contentCategory: "アニメ",
      eventName: "大洗あんこう祭・ガルパン関連イベント",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: 100000,
      economicImpact: 168700000,
      economicImpactPerPerson: 1687,
      hasEvent: true,
      memo: "大洗あんこう祭2023の来場者数として約10万人。経済効果は未確認のため空欄。",
    },
    {
      year: 2024,
      prefecture: "茨城県",
      municipality: "大洗町",
      dataType: "アニメ",
      contentTitle: "ガールズ&パンツァー",
      contentCategory: "アニメ",
      eventName: "大洗あんこう祭・ガルパン関連イベント",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 366,
      visitors: 135000,
      economicImpact: 227745000,
      economicImpactPerPerson: 1687,
      hasEvent: true,
      memo: "大洗観光協会の2025開催レポート内で前年135,000人と記載。経済効果は未確認のため空欄。",
    },
    {
      year: 2025,
      prefecture: "茨城県",
      municipality: "大洗町",
      dataType: "アニメ",
      contentTitle: "ガールズ&パンツァー",
      contentCategory: "アニメ",
      eventName: "大洗あんこう祭・ガルパン関連イベント",
      startDate: toIsoDate("2025/11/15"),
      endDate: toIsoDate("2025/11/16"),
      durationDays: 2,
      visitors: 155000,
      economicImpact: 261485000,
      economicImpactPerPerson: 1687,
      hasEvent: true,
      memo: "大洗観光協会の令和7年度開催レポート。2日間合計155,000人。経済効果は未確認のため空欄。",
    },
    {
      year: 2023,
      prefecture: "静岡県",
      municipality: "沼津市",
      dataType: "アニメ",
      contentTitle: "ラブライブ！サンシャイン!!",
      contentCategory: "アニメ",
      eventName: "聖地巡礼・沼津まち歩き",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2023年単独の公表値は未確認。参考：2017年の聖地巡礼関連増分は302,859〜381,944人、経済効果は約50.8〜61.4億円の試算あり。",
    },
    {
      year: 2024,
      prefecture: "静岡県",
      municipality: "沼津市",
      dataType: "アニメ",
      contentTitle: "ラブライブ！サンシャイン!!",
      contentCategory: "アニメ",
      eventName: "聖地巡礼・沼津まち歩き",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 366,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2024年単独の公表値は未確認。沼津市観光振興ビジョンに市全体の観光交流客数資料あり。",
    },
    {
      year: 2025,
      prefecture: "静岡県",
      municipality: "沼津市",
      dataType: "アニメ",
      contentTitle: "ラブライブ！サンシャイン!!",
      contentCategory: "アニメ",
      eventName: "聖地巡礼・沼津まち歩き",
      startDate: toIsoDate("2025/1/1"),
      endDate: toIsoDate("2025/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2025年単独の公表値は未確認。作品単独値が確認できたら追記。",
    },
    {
      year: 2020,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2020/1/1"),
      endDate: toIsoDate("2020/12/31"),
      durationDays: 365,
      visitors: 55211,
      economicImpact: 2671970000,
      economicImpactPerPerson: 48396,
      hasEvent: true,
      memo: "",
    },
    {
      year: 2021,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2021/1/1"),
      endDate: toIsoDate("2021/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "",
    },
    {
      year: 2022,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2022/1/1"),
      endDate: toIsoDate("2022/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "",
    },
    {
      year: 2023,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2023年単独の総観光客数・経済効果は未確認。麦わらの一味像周辺の来訪分析あり。",
    },
    {
      year: 2024,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2024年単独の総観光客数・経済効果は未確認。麦わらの一味像周辺の来訪分析あり。",
    },
    {
      year: 2025,
      prefecture: "熊本県",
      municipality: "熊本市",
      dataType: "漫画",
      contentTitle: "ONE PIECE",
      contentCategory: "漫画",
      eventName: "ONE PIECE熊本復興プロジェクト巡り",
      startDate: toIsoDate("2025/1/1"),
      endDate: toIsoDate("2025/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2025年単独の総観光客数・経済効果は未確認。確認後に追記。",
    },
    {
      year: 2021,
      prefecture: "大分県",
      municipality: "日田市",
      dataType: "漫画",
      contentTitle: "進撃の巨人",
      contentCategory: "漫画",
      eventName: "進撃の巨人 in HITA ミュージアム・聖地巡礼",
      startDate: toIsoDate("2021/1/1"),
      endDate: toIsoDate("2021/12/31"),
      durationDays: 365,
      visitors: 110000,
      economicImpact: 2050000000,
      economicImpactPerPerson: 18645,
      hasEvent: true,
      memo: "",
    },
    {
      year: 2022,
      prefecture: "大分県",
      municipality: "日田市",
      dataType: "漫画",
      contentTitle: "進撃の巨人",
      contentCategory: "漫画",
      eventName: "進撃の巨人 in HITA ミュージアム・聖地巡礼",
      startDate: toIsoDate("2022/1/1"),
      endDate: toIsoDate("2022/12/31"),
      durationDays: 365,
      visitors: 99000,
      economicImpact: 1850000000,
      economicImpactPerPerson: 18645,
      hasEvent: true,
      memo: "",
    },
    {
      year: 2023,
      prefecture: "大分県",
      municipality: "日田市",
      dataType: "漫画",
      contentTitle: "進撃の巨人",
      contentCategory: "漫画",
      eventName: "進撃の巨人 in HITA ミュージアム・聖地巡礼",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: 86000,
      economicImpact: 1600000000,
      economicImpactPerPerson: 18645,
      hasEvent: true,
      memo: "日田市公式FAQ：R5年の推計経済効果16億円。来場者数の年別値は未確認。",
    },
    {
      year: 2024,
      prefecture: "大分県",
      municipality: "日田市",
      dataType: "漫画",
      contentTitle: "進撃の巨人",
      contentCategory: "漫画",
      eventName: "進撃の巨人 in HITA ミュージアム・聖地巡礼",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 365,
      visitors: 96000,
      economicImpact: 1790000000,
      economicImpactPerPerson: 18645,
      hasEvent: true,
      memo: "日田市公式FAQ：R6年の推計経済効果17億9千万円。来場者数の年別値は未確認。",
    },
    {
      year: 2025,
      prefecture: "大分県",
      municipality: "日田市",
      dataType: "漫画",
      contentTitle: "進撃の巨人",
      contentCategory: "漫画",
      eventName: "進撃の巨人 in HITA ミュージアム・聖地巡礼",
      startDate: toIsoDate("2025/1/1"),
      endDate: toIsoDate("2025/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "",
    },
    {
      year: 2023,
      prefecture: "鳥取県",
      municipality: "北栄町",
      dataType: "漫画",
      contentTitle: "名探偵コナン",
      contentCategory: "漫画",
      eventName: "青山剛昌ふるさと館・コナンのまち巡り",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2023年単独の来館者数・経済効果は未確認。",
    },
    {
      year: 2024,
      prefecture: "鳥取県",
      municipality: "北栄町",
      dataType: "漫画",
      contentTitle: "名探偵コナン",
      contentCategory: "漫画",
      eventName: "青山剛昌ふるさと館・コナンのまち巡り",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2024年単独の来館者数・経済効果は未確認。",
    },
    {
      year: 2025,
      prefecture: "鳥取県",
      municipality: "北栄町",
      dataType: "漫画",
      contentTitle: "名探偵コナン",
      contentCategory: "漫画",
      eventName: "青山剛昌ふるさと館・コナンのまち巡り",
      startDate: toIsoDate("2025/1/1"),
      endDate: toIsoDate("2025/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "青山剛昌ふるさと館は2025/3/23に累計入館者200万人達成。年別値ではないため観光客数欄は空欄。",
    },
    {
      year: 2023,
      prefecture: "鳥取県",
      municipality: "境港市",
      dataType: "漫画",
      contentTitle: "ゲゲゲの鬼太郎",
      contentCategory: "漫画",
      eventName: "水木しげるロード・水木しげる記念館巡り",
      startDate: toIsoDate("2023/1/1"),
      endDate: toIsoDate("2023/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2023年単独の入力値は未確認。水木しげるロードは過去に入込客数が公表されている。",
    },
    {
      year: 2024,
      prefecture: "鳥取県",
      municipality: "境港市",
      dataType: "漫画",
      contentTitle: "ゲゲゲの鬼太郎",
      contentCategory: "漫画",
      eventName: "水木しげるロード・水木しげる記念館巡り",
      startDate: toIsoDate("2024/1/1"),
      endDate: toIsoDate("2024/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2024年単独の入力値は未確認。水木しげるロードは過去に入込客数が公表されている。",
    },
    {
      year: 2025,
      prefecture: "鳥取県",
      municipality: "境港市",
      dataType: "漫画",
      contentTitle: "ゲゲゲの鬼太郎",
      contentCategory: "漫画",
      eventName: "水木しげるロード・水木しげる記念館巡り",
      startDate: toIsoDate("2025/1/1"),
      endDate: toIsoDate("2025/12/31"),
      durationDays: 365,
      visitors: "",
      economicImpact: "",
      economicImpactPerPerson: "",
      hasEvent: true,
      memo: "2025年単独の入力値は未確認。確認後に追記。",
    },
  ];

  return rows.map((row, index) => ({
    id: createSampleId(index + 1),
    ...row,
    createdAt: now,
    updatedAt: now,
  }));
}
